/* Luxury fleet catalogue — NO PRICES.
   Inspired by public listings (e.g. U Drive Luxury Rentals AU) + common AU VIP fleet models.
   Specs are typical published figures for the model variant. */
window.ELITE_FLEET = [
  /* ── From U Drive garage ── */
  {
    id: 'mclaren-570s',
    brand: 'McLaren',
    model: '570S Coupe',
    year: '2017–2021',
    type: 'Supercar',
    seats: 2,
    doors: 2,
    topSpeed: '328 km/h',
    acceleration: '0–100 in 3.2s',
    engine: '3.8L twin-turbo V8',
    power: '570 PS',
    transmission: '7-speed dual-clutch',
    drivetrain: 'RWD',
    colours: ['Orange', 'White', 'Silver'],
    tags: ['supercar', 'track', 'weekend'],
    image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=900&q=80',
    summary: 'Addictive mid-engine supercar with Adaptive dampers and Sport/Track modes for ultimate driver engagement.'
  },
  {
    id: 'lambo-aventador-s-roadster',
    brand: 'Lamborghini',
    model: 'Aventador S Roadster',
    year: '2017–2021',
    type: 'Supercar',
    seats: 2,
    doors: 2,
    topSpeed: '350 km/h',
    acceleration: '0–100 in 3.0s',
    engine: '6.5L naturally aspirated V12',
    power: '740 PS',
    transmission: '7-speed ISR',
    drivetrain: 'AWD',
    colours: ['Yellow', 'Black', 'White'],
    tags: ['supercar', 'convertible', 'statement'],
    image: 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=900&q=80',
    summary: 'Open-top V12 icon — aggressive lines, scissor doors and unmistakable Italian presence for red-carpet arrivals.'
  },
  {
    id: 'lambo-huracan-awd',
    brand: 'Lamborghini',
    model: 'Huracán AWD',
    year: '2019–2023',
    type: 'Supercar',
    seats: 2,
    doors: 2,
    topSpeed: '325 km/h',
    acceleration: '0–100 in 2.9s',
    engine: '5.2L naturally aspirated V10',
    power: '640 PS',
    transmission: '7-speed dual-clutch',
    drivetrain: 'AWD',
    colours: ['White', 'Orange'],
    tags: ['supercar', 'awd', 'weekend'],
    image: 'https://images.unsplash.com/photo-1519245659620-e859806a8d3b?auto=format&fit=crop&w=900&q=80',
    summary: 'Sharp angular supercar with a roaring V10 soundtrack. Available in white and orange.'
  },
  {
    id: 'lambo-huracan-tecnica',
    brand: 'Lamborghini',
    model: 'Huracán Tecnica',
    year: '2022–2024',
    type: 'Supercar',
    seats: 2,
    doors: 2,
    topSpeed: '325 km/h',
    acceleration: '0–100 in 3.2s',
    engine: '5.2L naturally aspirated V10',
    power: '640 PS',
    transmission: '7-speed dual-clutch',
    drivetrain: 'RWD',
    colours: ['Green', 'Grey', 'Yellow'],
    tags: ['supercar', 'track', 'rwd'],
    image: 'https://images.unsplash.com/photo-1566473965997-3de9c817e938?auto=format&fit=crop&w=900&q=80',
    summary: 'Track-focused V10 supercar balancing STO intensity with road comfort and visceral sound.'
  },
  {
    id: 'lambo-urus-performante',
    brand: 'Lamborghini',
    model: 'Urus Performante',
    year: '2022–2025',
    type: 'SUV',
    seats: 5,
    doors: 5,
    topSpeed: '306 km/h',
    acceleration: '0–100 in 3.3s',
    engine: '4.0L twin-turbo V8',
    power: '666 PS',
    transmission: '8-speed automatic',
    drivetrain: 'AWD',
    colours: ['Black', 'Grey', 'Yellow'],
    tags: ['suv', 'family', 'performance'],
    image: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=900&q=80',
    summary: 'Peak Super SUV — reduced weight, aggressive aero and blistering twin-turbo V8 performance.'
  },
  {
    id: 'lambo-urus',
    brand: 'Lamborghini',
    model: 'Urus',
    year: '2020–2025',
    type: 'SUV',
    seats: 5,
    doors: 5,
    topSpeed: '305 km/h',
    acceleration: '0–100 in 3.6s',
    engine: '4.0L twin-turbo V8',
    power: '650 PS',
    transmission: '8-speed automatic',
    drivetrain: 'AWD',
    colours: ['Black', 'White'],
    tags: ['suv', 'family', 'vip'],
    image: 'https://images.unsplash.com/photo-1606220838315-056192d5e927?auto=format&fit=crop&w=900&q=80',
    summary: 'World-first Super SUV — high-speed capability with everyday versatility. Black or white.'
  },
  {
    id: 'ferrari-488-pista',
    brand: 'Ferrari',
    model: '488 Pista',
    year: '2018–2020',
    type: 'Supercar',
    seats: 2,
    doors: 2,
    topSpeed: '340 km/h',
    acceleration: '0–100 in 2.85s',
    engine: '3.9L twin-turbo V8',
    power: '720 PS',
    transmission: '7-speed dual-clutch',
    drivetrain: 'RWD',
    colours: ['Rosso Corsa', 'Yellow', 'White'],
    tags: ['supercar', 'track', 'icon'],
    image: 'https://images.unsplash.com/photo-1583121274602-3e282f38bc0f?auto=format&fit=crop&w=900&q=80',
    summary: 'Ferrari’s most powerful V8 special series — race tech transferred from Challenge and GTE programs.'
  },
  {
    id: 'audi-r8',
    brand: 'Audi',
    model: 'R8 V10',
    year: '2019–2023',
    type: 'Supercar',
    seats: 2,
    doors: 2,
    topSpeed: '330 km/h',
    acceleration: '0–100 in 3.1s',
    engine: '5.2L naturally aspirated V10',
    power: '620 PS',
    transmission: '7-speed dual-clutch',
    drivetrain: 'AWD',
    colours: ['Red', 'White', 'Matte Black'],
    tags: ['supercar', 'awd', 'weekend'],
    image: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=900&q=80',
    summary: 'Mid-engine V10 precision supercar. Available in red, white and matte black.'
  },
  {
    id: 'audi-rs-q8',
    brand: 'Audi',
    model: 'RS Q8',
    year: '2021–2025',
    type: 'SUV',
    seats: 5,
    doors: 5,
    topSpeed: '305 km/h',
    acceleration: '0–100 in 3.8s',
    engine: '4.0L twin-turbo V8',
    power: '600 PS',
    transmission: '8-speed tiptronic',
    drivetrain: 'AWD',
    colours: ['Nardo Grey', 'Black', 'White'],
    tags: ['suv', 'family', 'performance'],
    image: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=900&q=80',
    summary: 'Apex performance SUV — aggressive RS bodywork, twin-turbo V8 and luxury cabin.'
  },
  {
    id: 'audi-rs7',
    brand: 'Audi',
    model: 'RS7 Sportback',
    year: '2021–2025',
    type: 'Sedan',
    seats: 5,
    doors: 5,
    topSpeed: '305 km/h',
    acceleration: '0–100 in 3.6s',
    engine: '4.0L twin-turbo V8',
    power: '600 PS',
    transmission: '8-speed tiptronic',
    drivetrain: 'AWD',
    colours: ['Grey', 'Black', 'Blue'],
    tags: ['sedan', 'executive', 'performance'],
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80',
    summary: 'Four-door coupe supercar performance with wide stance and RS detailing.'
  },
  {
    id: 'audi-rs3',
    brand: 'Audi',
    model: 'RS3',
    year: '2022–2025',
    type: 'Sedan',
    seats: 5,
    doors: 4,
    topSpeed: '290 km/h',
    acceleration: '0–100 in 3.8s',
    engine: '2.5L turbo five-cylinder',
    power: '400 PS',
    transmission: '7-speed dual-clutch',
    drivetrain: 'AWD',
    colours: ['Green', 'Grey', 'White'],
    tags: ['sedan', 'compact', 'performance'],
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=80',
    summary: 'Compact sports rocket with iconic five-cylinder soundtrack and RS styling.'
  },
  {
    id: 'mercedes-amg-gt',
    brand: 'Mercedes-AMG',
    model: 'AMG GT',
    year: '2018–2023',
    type: 'Supercar',
    seats: 2,
    doors: 2,
    topSpeed: '318 km/h',
    acceleration: '0–100 in 3.8s',
    engine: '4.0L biturbo V8',
    power: '585 PS',
    transmission: '7-speed dual-clutch',
    drivetrain: 'RWD',
    colours: ['Silver', 'Black', 'Yellow'],
    tags: ['supercar', 'gt', 'weekend'],
    image: 'https://images.unsplash.com/photo-1618843479619-f3d0d81e4d10?auto=format&fit=crop&w=900&q=80',
    summary: 'Handcrafted AMG V8 grand tourer — long hood, fastback elegance and pure performance.'
  },
  {
    id: 'mercedes-gt63s',
    brand: 'Mercedes-AMG',
    model: 'GT 63 S 4-Door',
    year: '2020–2025',
    type: 'Sedan',
    seats: 4,
    doors: 4,
    topSpeed: '315 km/h',
    acceleration: '0–100 in 3.2s',
    engine: '4.0L biturbo V8',
    power: '639 PS',
    transmission: '9-speed MCT',
    drivetrain: 'AWD',
    colours: ['Black', 'Silver', 'White'],
    tags: ['sedan', 'executive', 'performance'],
    image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=900&q=80',
    summary: 'Four-door GT pinnacle — Panamericana grille, muscular proportions and staggering acceleration.'
  },
  {
    id: 'mercedes-e63s',
    brand: 'Mercedes-AMG',
    model: 'E 63 S AMG',
    year: '2021–2024',
    type: 'Sedan',
    seats: 5,
    doors: 4,
    topSpeed: '300 km/h',
    acceleration: '0–100 in 3.4s',
    engine: '4.0L biturbo V8',
    power: '612 PS',
    transmission: '9-speed MCT',
    drivetrain: 'AWD',
    colours: ['Black', 'White', 'Grey'],
    tags: ['sedan', 'executive', 'chauffeur'],
    image: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=900&q=80',
    summary: 'Executive rocket sedan — AMG power with E-Class luxury for VIP transfers.'
  },
  {
    id: 'mercedes-c63s',
    brand: 'Mercedes-AMG',
    model: 'C 63 S AMG',
    year: '2019–2023',
    type: 'Sedan',
    seats: 5,
    doors: 4,
    topSpeed: '290 km/h',
    acceleration: '0–100 in 3.9s',
    engine: '4.0L biturbo V8',
    power: '510 PS',
    transmission: '9-speed MCT',
    drivetrain: 'RWD',
    colours: ['White', 'Black', 'Grey'],
    tags: ['sedan', 'compact', 'performance'],
    image: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=80',
    summary: 'Compact high-performance luxury with explosive V8 character.'
  },
  {
    id: 'mercedes-g63',
    brand: 'Mercedes-AMG',
    model: 'G 63 AMG',
    year: '2020–2025',
    type: 'SUV',
    seats: 5,
    doors: 5,
    topSpeed: '240 km/h',
    acceleration: '0–100 in 4.5s',
    engine: '4.0L twin-turbo V8',
    power: '585 PS',
    transmission: '9-speed automatic',
    drivetrain: 'AWD',
    colours: ['White (black int.)', 'White (red int.)', 'Green', 'Matte Black'],
    tags: ['suv', 'statement', 'vip'],
    image: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80',
    summary: 'Iconic G-Wagen with AMG thunder. Multiple interior/exterior colourways available.'
  },
  {
    id: 'bmw-m3-comp',
    brand: 'BMW',
    model: 'M3 Competition',
    year: '2021–2025',
    type: 'Sedan',
    seats: 5,
    doors: 4,
    topSpeed: '290 km/h',
    acceleration: '0–100 in 3.9s',
    engine: '3.0L twin-turbo I6',
    power: '510 PS',
    transmission: '8-speed automatic',
    drivetrain: 'RWD / xDrive',
    colours: ['Isle of Man Green', 'Black', 'White'],
    tags: ['sedan', 'performance', 'weekend'],
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=80',
    summary: 'Iconic M sports sedan — high-rev twin-turbo six, aggressive aero and driver focus.'
  },
  {
    id: 'bmw-m5-comp',
    brand: 'BMW',
    model: 'M5 Competition',
    year: '2021–2024',
    type: 'Sedan',
    seats: 5,
    doors: 4,
    topSpeed: '305 km/h',
    acceleration: '0–100 in 3.3s',
    engine: '4.4L twin-turbo V8',
    power: '625 PS',
    transmission: '8-speed automatic',
    drivetrain: 'AWD (xDrive)',
    colours: ['Blue', 'Black', 'Grey'],
    tags: ['sedan', 'executive', 'performance'],
    image: 'https://images.unsplash.com/photo-1617531653520-bd466e6324e6?auto=format&fit=crop&w=900&q=80',
    summary: 'Super-sedan with M TwinPower V8, adaptive suspension and intelligent AWD.'
  },
  {
    id: 'bmw-m4-comp',
    brand: 'BMW',
    model: 'M4 Competition',
    year: '2021–2025',
    type: 'Coupe',
    seats: 4,
    doors: 2,
    topSpeed: '290 km/h',
    acceleration: '0–100 in 3.9s',
    engine: '3.0L twin-turbo I6',
    power: '510 PS',
    transmission: '8-speed automatic',
    drivetrain: 'RWD / xDrive',
    colours: ['Yellow', 'Black', 'White'],
    tags: ['coupe', 'performance', 'weekend'],
    image: 'https://images.unsplash.com/photo-1617814076668-0e4e8a2a0c5d?auto=format&fit=crop&w=900&q=80',
    summary: 'Muscular M coupe with distinctive kidney grille and track-ready dynamics.'
  },
  {
    id: 'rr-sport',
    brand: 'Land Rover',
    model: 'Range Rover Sport',
    year: '2022–2025',
    type: 'SUV',
    seats: 5,
    doors: 5,
    topSpeed: '234 km/h',
    acceleration: '0–100 in 5.9s',
    engine: '3.0L mild-hybrid I6',
    power: '360 PS',
    transmission: '8-speed automatic',
    drivetrain: 'AWD',
    colours: ['Santorini Black', 'White', 'Grey'],
    tags: ['suv', 'luxury', 'chauffeur'],
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=80',
    summary: 'Commanding luxury SUV — refined power with Range Rover presence for VIP arrivals.'
  },

  /* ── Additional AU VIP fleet favourites ── */
  {
    id: 'rr-cullinan',
    brand: 'Rolls-Royce',
    model: 'Cullinan',
    year: '2021–2025',
    type: 'SUV',
    seats: 5,
    doors: 5,
    topSpeed: '250 km/h',
    acceleration: '0–100 in 5.2s',
    engine: '6.75L twin-turbo V12',
    power: '571 PS',
    transmission: '8-speed automatic',
    drivetrain: 'AWD',
    colours: ['Black', 'White', 'Silver'],
    tags: ['suv', 'wedding', 'vip', 'chauffeur'],
    image: 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?auto=format&fit=crop&w=900&q=80',
    summary: 'Ultimate luxury SUV for weddings and executive transport — whisper-quiet V12 opulence.'
  },
  {
    id: 'rr-phantom',
    brand: 'Rolls-Royce',
    model: 'Phantom',
    year: '2019–2025',
    type: 'Sedan',
    seats: 5,
    doors: 4,
    topSpeed: '250 km/h',
    acceleration: '0–100 in 5.3s',
    engine: '6.75L twin-turbo V12',
    power: '571 PS',
    transmission: '8-speed automatic',
    drivetrain: 'RWD',
    colours: ['Black', 'White', 'Two-tone'],
    tags: ['sedan', 'wedding', 'vip', 'chauffeur'],
    image: 'https://images.unsplash.com/photo-1563720360172-67b8f3dce741?auto=format&fit=crop&w=900&q=80',
    summary: 'Flagship chauffeur saloon — the definitive red-carpet arrival vehicle.'
  },
  {
    id: 'rr-ghost',
    brand: 'Rolls-Royce',
    model: 'Ghost',
    year: '2021–2025',
    type: 'Sedan',
    seats: 5,
    doors: 4,
    topSpeed: '250 km/h',
    acceleration: '0–100 in 4.8s',
    engine: '6.75L twin-turbo V12',
    power: '571 PS',
    transmission: '8-speed automatic',
    drivetrain: 'AWD',
    colours: ['Silver', 'Black', 'White'],
    tags: ['sedan', 'wedding', 'vip'],
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80',
    summary: 'Contemporary Rolls-Royce presence with effortless V12 propulsion.'
  },
  {
    id: 'bentley-continental-gt',
    brand: 'Bentley',
    model: 'Continental GT',
    year: '2020–2025',
    type: 'Coupe',
    seats: 4,
    doors: 2,
    topSpeed: '333 km/h',
    acceleration: '0–100 in 3.7s',
    engine: '6.0L twin-turbo W12 / 4.0L V8',
    power: '550–650 PS',
    transmission: '8-speed dual-clutch',
    drivetrain: 'AWD',
    colours: ['British Racing Green', 'Black', 'White'],
    tags: ['coupe', 'wedding', 'gt'],
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=80',
    summary: 'Handcrafted grand tourer — British luxury and devastating pace for special occasions.'
  },
  {
    id: 'bentley-bentayga',
    brand: 'Bentley',
    model: 'Bentayga',
    year: '2021–2025',
    type: 'SUV',
    seats: 5,
    doors: 5,
    topSpeed: '290 km/h',
    acceleration: '0–100 in 4.5s',
    engine: '4.0L twin-turbo V8',
    power: '550 PS',
    transmission: '8-speed automatic',
    drivetrain: 'AWD',
    colours: ['Black', 'White', 'Blue'],
    tags: ['suv', 'wedding', 'vip', 'family'],
    image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=900&q=80',
    summary: 'Ultra-luxury SUV for bridal parties and executive families.'
  },
  {
    id: 'porsche-911-turbo-s',
    brand: 'Porsche',
    model: '911 Turbo S',
    year: '2021–2025',
    type: 'Supercar',
    seats: 4,
    doors: 2,
    topSpeed: '330 km/h',
    acceleration: '0–100 in 2.7s',
    engine: '3.8L twin-turbo flat-6',
    power: '650 PS',
    transmission: '8-speed PDK',
    drivetrain: 'AWD',
    colours: ['GT Silver', 'Black', 'White'],
    tags: ['supercar', 'weekend', 'icon'],
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80',
    summary: 'Everyday usable hyper-performance 911 — legendary AWD traction and iconic shape.'
  },
  {
    id: 'porsche-taycan',
    brand: 'Porsche',
    model: 'Taycan Turbo',
    year: '2022–2025',
    type: 'Sedan',
    seats: 4,
    doors: 4,
    topSpeed: '260 km/h',
    acceleration: '0–100 in 3.2s',
    engine: 'Dual electric motors',
    power: '680 PS',
    transmission: '2-speed rear',
    drivetrain: 'AWD',
    colours: ['Frozen Blue', 'White', 'Black'],
    tags: ['sedan', 'electric', 'executive'],
    image: 'https://images.unsplash.com/photo-1614200179396-2bdb77ebf81b?auto=format&fit=crop&w=900&q=80',
    summary: 'All-electric Porsche grand tourer — silent thrust with sports-car DNA.'
  },
  {
    id: 'mclaren-720s',
    brand: 'McLaren',
    model: '720S',
    year: '2018–2023',
    type: 'Supercar',
    seats: 2,
    doors: 2,
    topSpeed: '341 km/h',
    acceleration: '0–100 in 2.9s',
    engine: '4.0L twin-turbo V8',
    power: '720 PS',
    transmission: '7-speed dual-clutch',
    drivetrain: 'RWD',
    colours: ['Papaya Spark', 'Black', 'White'],
    tags: ['supercar', 'track', 'weekend'],
    image: 'https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&w=900&q=80',
    summary: 'Dihedral-door supercar with extreme aero and track-honed agility.'
  },
  {
    id: 'aston-db11',
    brand: 'Aston Martin',
    model: 'DB11',
    year: '2019–2023',
    type: 'Coupe',
    seats: 4,
    doors: 2,
    topSpeed: '322 km/h',
    acceleration: '0–100 in 3.9s',
    engine: '5.2L twin-turbo V12 / 4.0L V8',
    power: '510–630 PS',
    transmission: '8-speed automatic',
    drivetrain: 'RWD',
    colours: ['Racing Green', 'Silver', 'Black'],
    tags: ['coupe', 'gt', 'wedding'],
    image: 'https://images.unsplash.com/photo-1606220838315-056192d5e927?auto=format&fit=crop&w=900&q=80',
    summary: 'British GT elegance — perfect statement coupe for formal events.'
  },
  {
    id: 'ferrari-roma',
    brand: 'Ferrari',
    model: 'Roma',
    year: '2021–2025',
    type: 'Coupe',
    seats: 4,
    doors: 2,
    topSpeed: '320 km/h',
    acceleration: '0–100 in 3.4s',
    engine: '3.9L twin-turbo V8',
    power: '620 PS',
    transmission: '8-speed dual-clutch',
    drivetrain: 'RWD',
    colours: ['Rosso', 'Grey', 'Black'],
    tags: ['coupe', 'gt', 'weekend'],
    image: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=900&q=80',
    summary: 'La Nuova Dolce Vita — elegant Ferrari grand tourer for stylish arrivals.'
  },
  {
    id: 'tesla-plaid',
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: '2022–2025',
    type: 'Sedan',
    seats: 5,
    doors: 4,
    topSpeed: '322 km/h',
    acceleration: '0–100 in 2.1s',
    engine: 'Tri-motor electric',
    power: '1,020 PS',
    transmission: 'Single-speed',
    drivetrain: 'AWD',
    colours: ['Midnight Silver', 'White', 'Red'],
    tags: ['sedan', 'electric', 'executive'],
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=900&q=80',
    summary: 'Hyper-acceleration EV sedan for futuristic VIP transfers.'
  },

  /* ── Motorcycles ── */
  {
    id: 'ducati-panigale-v4',
    brand: 'Ducati',
    model: 'Panigale V4',
    year: '2022–2025',
    type: 'Motorcycle',
    seats: 1,
    doors: 0,
    topSpeed: '300+ km/h',
    acceleration: '0–100 in ~2.9s',
    engine: '1.1L Desmosedici Stradale V4',
    power: '215 PS',
    transmission: '6-speed',
    drivetrain: 'RWD (chain)',
    colours: ['Ducati Red', 'Black'],
    tags: ['motorcycle', 'sportbike', 'weekend'],
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=900&q=80',
    summary: 'MotoGP-derived superbike for thrill rides and photo shoots (experienced riders).'
  },
  {
    id: 'bmw-s1000rr',
    brand: 'BMW Motorrad',
    model: 'S 1000 RR',
    year: '2021–2025',
    type: 'Motorcycle',
    seats: 1,
    doors: 0,
    topSpeed: '299 km/h',
    acceleration: '0–100 in ~3.1s',
    engine: '999cc inline-4',
    power: '210 PS',
    transmission: '6-speed',
    drivetrain: 'RWD (chain)',
    colours: ['Racing Red', 'White/Blue/Red'],
    tags: ['motorcycle', 'sportbike', 'track'],
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=900&q=80',
    summary: 'German superbike precision for track days and content shoots.'
  },
  {
    id: 'harley-road-king',
    brand: 'Harley-Davidson',
    model: 'Road King',
    year: '2020–2024',
    type: 'Motorcycle',
    seats: 2,
    doors: 0,
    topSpeed: '180 km/h',
    acceleration: '—',
    engine: 'Milwaukee-Eight 107 V-twin',
    power: '—',
    transmission: '6-speed',
    drivetrain: 'RWD (belt)',
    colours: ['Black', 'Chrome'],
    tags: ['motorcycle', 'cruiser', 'wedding'],
    image: 'https://images.unsplash.com/photo-1558980664-1db506751c6a?auto=format&fit=crop&w=900&q=80',
    summary: 'Classic American cruiser — ideal for wedding party escorts and scenic rides.'
  },
  {
    id: 'triumph-rocket-3',
    brand: 'Triumph',
    model: 'Rocket 3',
    year: '2021–2025',
    type: 'Motorcycle',
    seats: 2,
    doors: 0,
    topSpeed: '220 km/h',
    acceleration: '0–100 in ~2.8s',
    engine: '2.5L triple',
    power: '167 PS',
    transmission: '6-speed',
    drivetrain: 'RWD (shaft)',
    colours: ['Silver Ice', 'Black'],
    tags: ['motorcycle', 'cruiser', 'statement'],
    image: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?auto=format&fit=crop&w=900&q=80',
    summary: 'World’s largest production motorcycle engine — massive torque and road presence.'
  }
];

/* Brand meta for filter logos (Simple Icons CDN where available) */
window.ELITE_FLEET_BRANDS = [
  { id: 'all', name: 'All', logo: null },
  { id: 'Lamborghini', name: 'Lamborghini', logo: 'https://cdn.simpleicons.org/lamborghini/c9a84c' },
  { id: 'Ferrari', name: 'Ferrari', logo: 'https://cdn.simpleicons.org/ferrari/c9a84c' },
  { id: 'McLaren', name: 'McLaren', logo: 'https://cdn.simpleicons.org/mclaren/c9a84c' },
  { id: 'Porsche', name: 'Porsche', logo: 'https://cdn.simpleicons.org/porsche/c9a84c' },
  { id: 'Rolls-Royce', name: 'Rolls-Royce', logo: 'https://cdn.simpleicons.org/rollsroyce/c9a84c' },
  { id: 'Bentley', name: 'Bentley', logo: 'https://cdn.simpleicons.org/bentley/c9a84c' },
  { id: 'Mercedes-AMG', name: 'Mercedes-AMG', logo: 'https://cdn.simpleicons.org/mercedes/c9a84c' },
  { id: 'BMW', name: 'BMW', logo: 'https://cdn.simpleicons.org/bmw/c9a84c' },
  { id: 'Audi', name: 'Audi', logo: 'https://cdn.simpleicons.org/audi/c9a84c' },
  { id: 'Aston Martin', name: 'Aston Martin', logo: 'https://cdn.simpleicons.org/astonmartin/c9a84c' },
  { id: 'Land Rover', name: 'Land Rover', logo: 'https://cdn.simpleicons.org/landrover/c9a84c' },
  { id: 'Tesla', name: 'Tesla', logo: 'https://cdn.simpleicons.org/tesla/c9a84c' },
  { id: 'Ducati', name: 'Ducati', logo: 'https://cdn.simpleicons.org/ducati/c9a84c' },
  { id: 'BMW Motorrad', name: 'BMW Motorrad', logo: 'https://cdn.simpleicons.org/bmw/c9a84c' },
  { id: 'Harley-Davidson', name: 'Harley-Davidson', logo: 'https://cdn.simpleicons.org/harleydavidson/c9a84c' },
  { id: 'Triumph', name: 'Triumph', logo: 'https://cdn.simpleicons.org/triumph/c9a84c' }
];
