/* Luxury yacht / charter boat catalogue — NO PRICES.
   Inspired by public Sydney Harbour Exclusive charter fleet listings.
   Specs are public capacity/type details; all hires are quote-based. */
window.ELITE_YACHTS = [
  {
    id: "northern-escape",
    name: "Northern Escape",
    type: "Superyacht",
    sizeBand: "Intimate (≤20)",
    capacity: 12,
    capacityLabel: "12 guests",
    length: "41 m",
    location: "Sydney Harbour / Great Barrier Reef",
    crew: "Full professional crew",
    overnight: 12,
    cabins: 6,
    features: ["Jacuzzi", "Beach club", "Infinity pool", "Master suite", "Wine cellars", "Alfresco dining"],
    tags: ["superyacht", "overnight", "vip", "jacuzzi"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2025/09/FI-1.jpg",
    summary: "Stunning 41m superyacht with beach club, infinity pool, jacuzzi and flexible cabin layout for the ultimate private charter."
  },
  {
    id: "ghost-2",
    name: "Ghost 2",
    type: "Superyacht",
    sizeBand: "Large (101–200)",
    capacity: 110,
    capacityLabel: "110 guests",
    length: "Large motor yacht",
    location: "Sydney Harbour",
    crew: "Full professional crew",
    overnight: 12,
    cabins: 5,
    features: ["Jacuzzi", "Sundeck bar", "Bang & Olufsen AV", "Zero-speed stabilisers", "5 ensuite staterooms"],
    tags: ["superyacht", "corporate", "wedding", "overnight"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/Ghost-2-sydney-harbour-FI.jpg",
    summary: "One of the largest luxury charter yachts on the harbour — 110 cocktail guests, jet-black hull, sundeck jacuzzi and resort-level interiors."
  },
  {
    id: "shadow",
    name: "Shadow",
    type: "Motor Yacht",
    sizeBand: "Mid (51–100)",
    capacity: 90,
    capacityLabel: "90 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Spacious decks", "Cocktail functions", "Corporate ready"],
    tags: ["motor-yacht", "corporate", "party"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/Shadow-Sydney-FI-1-scaled.jpg",
    summary: "Sleek luxury motor yacht for up to 90 guests — ideal for corporate harbour events and stylish private celebrations."
  },
  {
    id: "quantum",
    name: "Quantum",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 45,
    capacityLabel: "45 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Modern interiors", "Open deck spaces"],
    tags: ["motor-yacht", "private", "corporate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/02/Quantum-Boat-Sydney-1.jpg",
    summary: "Contemporary motor yacht charter for up to 45 guests — premium private and corporate harbour cruising."
  },
  {
    id: "masteka-2",
    name: "MASTEKA 2",
    type: "Motor Yacht",
    sizeBand: "Mid (51–100)",
    capacity: 80,
    capacityLabel: "80 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Multi-deck layout", "Large entertaining areas"],
    tags: ["motor-yacht", "party", "corporate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/02/Masteka-2-boat-scaled.jpg",
    summary: "Impressive multi-deck motor yacht for up to 80 guests — strong choice for parties and corporate charters."
  },
  {
    id: "orraia",
    name: "Orraia",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 49,
    capacityLabel: "49 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Luxury fit-out", "Intimate entertaining"],
    tags: ["motor-yacht", "private", "vip"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2024/10/Orraia-boat-sydney-2.jpg",
    summary: "Elegant motor yacht for up to 49 guests — refined private charters and smaller corporate groups."
  },
  {
    id: "mischief",
    name: "Mischief",
    type: "Superyacht",
    sizeBand: "Large (101–200)",
    capacity: 180,
    capacityLabel: "180 guests",
    length: "Largest commercial AU",
    location: "Sydney Harbour",
    crew: "Full professional crew",
    overnight: null,
    cabins: null,
    features: ["Bow slide", "Climbing wall", "French Navy hull", "Water toys", "Entertainment deck"],
    tags: ["superyacht", "party", "statement", "water-toys"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2024/08/MISCHIEF-YACHT-4.jpg",
    summary: "Australia’s largest commercial superyacht — Francesco Paszkowski design with slide, climbing wall and unforgettable harbour presence."
  },
  {
    id: "bluestone",
    name: "Bluestone",
    type: "Motor Yacht",
    sizeBand: "Mid (51–100)",
    capacity: 90,
    capacityLabel: "90 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Spacious saloon", "Outdoor lounging"],
    tags: ["motor-yacht", "wedding", "party"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2023/08/FI.jpg",
    summary: "Popular harbour motor yacht for up to 90 guests — weddings, birthdays and corporate functions."
  },
  {
    id: "sirenuse",
    name: "Sirenuse",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 36,
    capacityLabel: "36 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2023/03/Sirenuse-yacht-sydney-scaled.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 36 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "oneworld",
    name: "ONEWORLD",
    type: "Motor Yacht",
    sizeBand: "Mid (51–100)",
    capacity: 100,
    capacityLabel: "100 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Large capacity", "Event-ready AV"],
    tags: ["motor-yacht", "party", "corporate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2018/04/ONEWORLD-13.jpg",
    summary: "High-capacity luxury yacht for up to 100 guests — perfect for bigger parties and product launches."
  },
  {
    id: "mohasuwei",
    name: "MOHASUWEI",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 36,
    capacityLabel: "36 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2019/02/FI.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 36 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "evolution",
    name: "Evolution",
    type: "Motor Yacht",
    sizeBand: "Mid (51–100)",
    capacity: 70,
    capacityLabel: "70 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Modern styling", "Flexible layouts"],
    tags: ["motor-yacht", "party", "corporate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/02/Evoltiuon-Yacht-Sydney-scaled.jpg",
    summary: "Modern luxury charter yacht for up to 70 guests with flexible event configurations."
  },
  {
    id: "corroboree",
    name: "Corroboree",
    type: "Function Boat",
    sizeBand: "Large (101–200)",
    capacity: 110,
    capacityLabel: "110 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Large cocktail capacity", "Multi-level decks"],
    tags: ["function", "party", "corporate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/02/corroboree1-1-1-Copy.jpg",
    summary: "Spacious function vessel for up to 110 guests — social and corporate harbour events."
  },
  {
    id: "lance",
    name: "Lance",
    type: "Superyacht",
    sizeBand: "Mid (51–100)",
    capacity: 80,
    capacityLabel: "80 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Luxury presentation", "Large guest capacity"],
    tags: ["superyacht", "vip", "corporate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2024/09/lance-yacht-sydney.jpg",
    summary: "Statement luxury yacht for up to 80 guests — VIP, red-carpet and exclusive private charters."
  },
  {
    id: "shore-thing",
    name: "Shore Thing",
    type: "Function Boat",
    sizeBand: "Mid (51–100)",
    capacity: 70,
    capacityLabel: "70 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2018/08/Shore-Thing-Boat-sydney.jpg",
    summary: "Sydney Harbour function boat charter for up to 70 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "belle",
    name: "Belle",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 36,
    capacityLabel: "36 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2023/12/Belle-Yacht-Sydney-7.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 36 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "oscar-2",
    name: "Oscar 2",
    type: "Function Boat",
    sizeBand: "Mid (51–100)",
    capacity: 60,
    capacityLabel: "60 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/MG_9774_0101-1-scaled.jpg",
    summary: "Sydney Harbour function boat charter for up to 60 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "legacy",
    name: "Legacy",
    type: "Motor Yacht",
    sizeBand: "Large (101–200)",
    capacity: 105,
    capacityLabel: "105 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Premium entertaining", "Flexible guest numbers"],
    tags: ["motor-yacht", "party", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2022/05/13-1.jpg",
    summary: "Premium motor yacht for up to 105 guests — standout option for large private and corporate charters."
  },
  {
    id: "my-seven-star",
    name: "Seven Star",
    type: "Function Boat",
    sizeBand: "Mid (51–100)",
    capacity: 75,
    capacityLabel: "75 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/SEVEN-STAR-5.jpg",
    summary: "Sydney Harbour function boat charter for up to 75 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "phoenix-one",
    name: "Phoenix One",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 46,
    capacityLabel: "46 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2024/07/15.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 46 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "sea-raes",
    name: "Sea Raes",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 34,
    capacityLabel: "34 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2025/02/sea-raes-aft-profile-scaled-1.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 34 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "caviar",
    name: "Caviar",
    type: "Function Boat",
    sizeBand: "Mid (51–100)",
    capacity: 65,
    capacityLabel: "65 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2019/04/lxRHv3r4-scaled.jpg",
    summary: "Sydney Harbour function boat charter for up to 65 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "a-q-a",
    name: "A.Q.A",
    type: "Function Boat",
    sizeBand: "Mid (51–100)",
    capacity: 90,
    capacityLabel: "90 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Large entertaining decks"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/AQA-charter-boat-sydney.jpg",
    summary: "Sydney Harbour function boat charter for up to 90 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "galaxy-1",
    name: "Galaxy 1",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 47,
    capacityLabel: "47 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2018/03/G1_Hero-1.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 47 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "aurora",
    name: "AURORA",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 33,
    capacityLabel: "33 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2018/05/12-1.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 33 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "ghost-1",
    name: "Ghost I",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 36,
    capacityLabel: "36 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/ghost1.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 36 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "lady-pamela",
    name: "Lady Pamela",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 34,
    capacityLabel: "34 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/2-4.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 34 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "empress",
    name: "Empress",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 36,
    capacityLabel: "36 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2024/09/Empress-Boat-Sydney-11.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 36 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "privacy",
    name: "Privacy",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 36,
    capacityLabel: "36 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2020/12/Picture1.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 36 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "salt",
    name: "SALT",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 49,
    capacityLabel: "49 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2022/02/67.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 49 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "prometheus",
    name: "Prometheus",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 36,
    capacityLabel: "36 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/PROMETHEUS-2020-10-scaled.jpeg",
    summary: "Sydney Harbour motor yacht charter for up to 36 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "rhemtide",
    name: "Rhemtide",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 47,
    capacityLabel: "47 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/Rhemtide-charter-boat-sydney.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 47 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "alfie-ii",
    name: "Alfie II",
    type: "Motor Yacht",
    sizeBand: "Intimate (≤20)",
    capacity: 12,
    capacityLabel: "12 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Intimate luxury"],
    tags: ["intimate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2025/09/ALFIE-EDITED-15-2.jpg-edm-scaled.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 12 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "mon-reve",
    name: "Mon Reve",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 32,
    capacityLabel: "32 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2020/02/14.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 32 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "enigma",
    name: "Enigma",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 41,
    capacityLabel: "41 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/m1R_npTA.jpeg",
    summary: "Sydney Harbour motor yacht charter for up to 41 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "gravity",
    name: "Gravity",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 30,
    capacityLabel: "30 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2026/07/GravityExterior2.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 30 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "ariston",
    name: "Ariston",
    type: "Function Boat",
    sizeBand: "Mid (51–100)",
    capacity: 58,
    capacityLabel: "58 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/Ariston-Boat-Sydney.jpg",
    summary: "Sydney Harbour function boat charter for up to 58 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "aquabay",
    name: "Aquabay",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 35,
    capacityLabel: "35 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/01-Aquabay-1.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 35 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "antares",
    name: "Antares",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 24,
    capacityLabel: "24 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2022/04/Antares-charter-boat-Sydney-1-scaled.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 24 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "sydney-seabird",
    name: "Sydney Seabird",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 40,
    capacityLabel: "40 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2022/02/1-1.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 40 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "sydney-crystal",
    name: "Sydney Crystal",
    type: "Function Boat",
    sizeBand: "Mid (51–100)",
    capacity: 80,
    capacityLabel: "80 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Large entertaining decks"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2024/08/Sydney-Crystal.jpg",
    summary: "Sydney Harbour function boat charter for up to 80 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "sir-thomas-sopwith",
    name: "Sir Thomas Sopwith",
    type: "Classic Vessel",
    sizeBand: "Private (21–50)",
    capacity: 25,
    capacityLabel: "25 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Classic lines", "Intimate charter"],
    tags: ["classic", "private", "unique"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2024/10/4-1.jpg",
    summary: "Classic vessel for up to 25 guests — elegant heritage feel for intimate occasions."
  },
  {
    id: "element",
    name: "Element",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 36,
    capacityLabel: "36 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2019/09/3-2.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 36 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "ohana",
    name: "Ohana",
    type: "Motor Yacht",
    sizeBand: "Intimate (≤20)",
    capacity: 12,
    capacityLabel: "12 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Intimate luxury"],
    tags: ["intimate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2025/09/Ohana-boat-sydney-fi.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 12 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "ginger",
    name: "Ginger",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 30,
    capacityLabel: "30 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2024/09/2.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 30 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "circa-spirit",
    name: "Circa Spirit",
    type: "Function Boat",
    sizeBand: "Mid (51–100)",
    capacity: 65,
    capacityLabel: "65 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2020/10/2.jpg",
    summary: "Sydney Harbour function boat charter for up to 65 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "john-oxley",
    name: "John Oxley",
    type: "Classic Vessel",
    sizeBand: "Private (21–50)",
    capacity: 50,
    capacityLabel: "50 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Heritage steamship character", "Unique photo backdrop"],
    tags: ["classic", "wedding", "unique"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/JohnOxley_321_1024x682-1.jpg",
    summary: "Historic harbour vessel for up to 50 guests — distinctive classic character for unique charters."
  },
  {
    id: "coisalinda",
    name: "Coisalinda",
    type: "Motor Yacht",
    sizeBand: "Intimate (≤20)",
    capacity: 10,
    capacityLabel: "10 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Intimate luxury"],
    tags: ["intimate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2025/03/Coisalinda-1-1.jpeg",
    summary: "Sydney Harbour motor yacht charter for up to 10 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "state-of-the-art",
    name: "State of the Art",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 40,
    capacityLabel: "40 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/State-of-the-art.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 40 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "the-ribbon",
    name: "The Ribbon",
    type: "Motor Yacht",
    sizeBand: "Intimate (≤20)",
    capacity: 12,
    capacityLabel: "12 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Intimate luxury"],
    tags: ["intimate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2022/01/FI-3.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 12 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "enterprise",
    name: "Enterprise",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 30,
    capacityLabel: "30 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/02/Enterprise-14-1.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 30 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "solaris",
    name: "Solaris",
    type: "Motor Yacht",
    sizeBand: "Intimate (≤20)",
    capacity: 12,
    capacityLabel: "12 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Intimate luxury"],
    tags: ["intimate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2025/01/Solaris-boat-sydney.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 12 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "isola",
    name: "Isola",
    type: "Motor Yacht",
    sizeBand: "Intimate (≤20)",
    capacity: 12,
    capacityLabel: "12 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Intimate luxury"],
    tags: ["intimate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2025/02/Isola-Boat-Sydney-1.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 12 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "felix",
    name: "Felix",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 25,
    capacityLabel: "25 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2021/06/6.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 25 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "seaduced",
    name: "Seaduced",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 22,
    capacityLabel: "22 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/stern-view-of-seaduced-luxury-boat-hire.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 22 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "como",
    name: "Como",
    type: "Motor Yacht",
    sizeBand: "Intimate (≤20)",
    capacity: 12,
    capacityLabel: "12 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Intimate luxury"],
    tags: ["intimate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2025/09/Como-boat-sydney-FI.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 12 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "platinum",
    name: "Platinum",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 22,
    capacityLabel: "22 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/boat-party-1-825x510.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 22 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "birchgrove",
    name: "Birchgrove",
    type: "Motor Yacht",
    sizeBand: "Intimate (≤20)",
    capacity: 16,
    capacityLabel: "16 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Intimate luxury"],
    tags: ["intimate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/Birchgrove-10-scaled.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 16 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "coco",
    name: "Coco",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 23,
    capacityLabel: "23 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2020/03/COCO-10.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 23 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "seaduction",
    name: "Seaduction",
    type: "Motor Yacht",
    sizeBand: "Private (21–50)",
    capacity: 22,
    capacityLabel: "22 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options"],
    tags: ["private"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/seaduction-31-825x510.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 22 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "impluse",
    name: "Impluse",
    type: "Motor Yacht",
    sizeBand: "Intimate (≤20)",
    capacity: 12,
    capacityLabel: "12 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Intimate luxury"],
    tags: ["intimate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2025/12/Impluse-boat-Sydney.jpg",
    summary: "Sydney Harbour motor yacht charter for up to 12 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "hamptons-sydney",
    name: "Hamptons Sydney",
    type: "Function Boat",
    sizeBand: "Mid (51–100)",
    capacity: 95,
    capacityLabel: "95 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Large entertaining decks"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2018/10/Gallery-3-scaled-1.jpg",
    summary: "Sydney Harbour function boat charter for up to 95 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "aussie-magic",
    name: "Aussie Magic",
    type: "Catamaran",
    sizeBand: "Large (101–200)",
    capacity: 200,
    capacityLabel: "200 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Stable twin hull", "Open social decks"],
    tags: ["catamaran", "party", "corporate"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/Aussie-825x510.jpg",
    summary: "Large social catamaran-style charter for up to 200 guests — parties, celebrations and team days."
  },
  {
    id: "blue-room",
    name: "Blue Room",
    type: "Event Vessel",
    sizeBand: "Mega event (200+)",
    capacity: 380,
    capacityLabel: "380 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Large entertaining decks", "Event production ready"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2021/04/Blue-room-boat-Sydney-FI.jpg",
    summary: "Sydney Harbour event vessel charter for up to 380 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "coast",
    name: "Coast",
    type: "Function Boat",
    sizeBand: "Large (101–200)",
    capacity: 150,
    capacityLabel: "150 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Large entertaining decks"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/COAST-1.jpg",
    summary: "Sydney Harbour function boat charter for up to 150 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "eclipse",
    name: "Eclipse",
    type: "Event Vessel",
    sizeBand: "Mega event (200+)",
    capacity: 240,
    capacityLabel: "240 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Large entertaining decks", "Event production ready"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2022/03/9.jpg",
    summary: "Sydney Harbour event vessel charter for up to 240 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "island",
    name: "The Island",
    type: "Event Vessel",
    sizeBand: "Large (101–200)",
    capacity: 200,
    capacityLabel: "200 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Large entertaining decks", "Event production ready"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/3.jpeg",
    summary: "Sydney Harbour event vessel charter for up to 200 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "starship-aqua",
    name: "Starship Aqua",
    type: "Event Vessel",
    sizeBand: "Mega event (200+)",
    capacity: 300,
    capacityLabel: "300 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Large function capacity", "Harbour views"],
    tags: ["event", "corporate", "party"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/6-2.jpg",
    summary: "Major function vessel for up to 300 guests — corporate and social harbour events."
  },
  {
    id: "the-jackson",
    name: "The Jackson",
    type: "Event Vessel",
    sizeBand: "Mega event (200+)",
    capacity: 700,
    capacityLabel: "700 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Mega capacity", "Harbour dining"],
    tags: ["event", "corporate", "mega"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2022/05/The-Jackson-Sydney-Harbour-1.jpg",
    summary: "Major function vessel for up to 700 guests — large-scale dining and entertainment on the harbour."
  },
  {
    id: "bella-vista",
    name: "Bella Vista",
    type: "Event Vessel",
    sizeBand: "Mega event (200+)",
    capacity: 800,
    capacityLabel: "800 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Mega capacity", "Multi-deck events"],
    tags: ["event", "corporate", "mega"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/Image-2.jpg",
    summary: "Huge multi-deck event vessel for up to 800 guests — conferences, galas and large celebrations."
  },
  {
    id: "the-starship",
    name: "The Starship",
    type: "Event Vessel",
    sizeBand: "Mega event (200+)",
    capacity: 950,
    capacityLabel: "950 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Mega capacity", "Full event production"],
    tags: ["event", "corporate", "mega"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2017/09/Starship2344a-1.jpg",
    summary: "Iconic mega event vessel for up to 950 guests — major corporate, gala and public-scale harbour events."
  },
  {
    id: "captain-cook-3",
    name: "Captain Cook 3",
    type: "Event Vessel",
    sizeBand: "Mega event (200+)",
    capacity: 300,
    capacityLabel: "300-400 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Large entertaining decks", "Event production ready"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2023/10/1.jpg",
    summary: "Sydney Harbour event vessel charter for up to 300-400 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "inception",
    name: "Inception",
    type: "Event Vessel",
    sizeBand: "Mega event (200+)",
    capacity: 413,
    capacityLabel: "413 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Professional crew", "Harbour cruising", "Catering options", "Large entertaining decks", "Event production ready"],
    tags: ["party", "corporate", "wedding"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2025/03/Inception-sydney-harbour.jpg",
    summary: "Sydney Harbour event vessel charter for up to 413 guests — fully crewed luxury hire for private, corporate and celebration events."
  },
  {
    id: "seadeck",
    name: "Seadeck",
    type: "Event Vessel",
    sizeBand: "Mega event (200+)",
    capacity: 420,
    capacityLabel: "420 guests",
    length: "—",
    location: "Sydney Harbour",
    crew: "Fully crewed",
    overnight: null,
    cabins: null,
    features: ["Large event spaces", "Flexible configurations"],
    tags: ["event", "corporate", "party"],
    image: "https://www.sydneyharbourexclusive.com/wp-content/uploads/2018/04/MGL9143_preview-1.jpeg",
    summary: "Large event vessel for 300–420 guests — product launches, awards and big social functions."
  }
];

/* Type filters (icons — yacht marques rarely use car-style logos) */
window.ELITE_YACHT_TYPES = [
  {
    "id": "all",
    "name": "All",
    "icon": "anchor"
  },
  {
    "id": "Superyacht",
    "name": "Superyacht",
    "icon": "yacht"
  },
  {
    "id": "Motor Yacht",
    "name": "Motor Yacht",
    "icon": "boat"
  },
  {
    "id": "Function Boat",
    "name": "Function",
    "icon": "glass"
  },
  {
    "id": "Event Vessel",
    "name": "Event Vessel",
    "icon": "spark"
  },
  {
    "id": "Catamaran",
    "name": "Catamaran",
    "icon": "waves"
  },
  {
    "id": "Classic Vessel",
    "name": "Classic",
    "icon": "classic"
  }
];

window.ELITE_YACHT_SIZES = [
  {
    "id": "all",
    "name": "Any size"
  },
  {
    "id": "Intimate (\u226420)",
    "name": "Intimate \u226420"
  },
  {
    "id": "Private (21\u201350)",
    "name": "Private 21\u201350"
  },
  {
    "id": "Mid (51\u2013100)",
    "name": "Mid 51\u2013100"
  },
  {
    "id": "Large (101\u2013200)",
    "name": "Large 101\u2013200"
  },
  {
    "id": "Mega event (200+)",
    "name": "Mega 200+"
  }
];

